# import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.gaussian_process import GaussianProcessRegressor
# from sklearn.gaussian_process.kernels import Matern, ConstantKernel, WhiteKernel
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

# data_path = "D:\KIT\cafm_lhs_500.npz"

# def run_deep_study(data_path):
#     # 1. Load Data
#     data = np.load(data_path)
#     X_raw = data['X']
#     Y_raw = data['Y']
    
#     # FOCUS: 1 Input (Density, idx=4) vs 1 Output (Mean Crossing Time, idx=0)
#     density_idx = 4
#     target_idx = 0
    
#     # Extract data and clean NaNs
#     y = Y_raw[:, target_idx]
#     valid_mask = ~np.isnan(y)
#     X_clean = X_raw[valid_mask]
#     y_clean = y[valid_mask]
    
#     # Train/Test Split
#     X_train, X_test, y_train, y_test = train_test_split(
#         X_clean, y_clean, test_size=0.2, random_state=42
#     )
    
#     # Sort test data by Density for clean plotting
#     sorted_idx = np.argsort(X_test[:, density_idx])
#     X_test_sorted = X_test[sorted_idx]
#     y_test_sorted = y_test[sorted_idx]
#     density_test = X_test_sorted[:, density_idx]

#     # 2. SCALING (Explicitly answering their question: YES, we scale)
#     scaler_X = StandardScaler()
#     scaler_y = StandardScaler()
    
#     X_train_scaled = scaler_X.fit_transform(X_train)
#     X_test_scaled = scaler_X.transform(X_test_sorted)
#     y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

#     # 3. Train GP (The Black Box)
#     kernel = ConstantKernel(1.0) * Matern(length_scale=np.ones(6), nu=2.5) + WhiteKernel(noise_level=0.1)
#     gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=5, random_state=42)
#     gp.fit(X_train_scaled, y_train_scaled)

#     # 4. PREDICT WITH COVARIANCE (The Math / Internal Relation)
#     # y_cov gives the full NxN covariance matrix, not just standard deviation!
#     y_pred_scaled, y_cov_scaled = gp.predict(X_test_scaled, return_cov=True)
    
#     # Inverse transform
#     y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
#     sigma = np.sqrt(np.diag(y_cov_scaled)) * scaler_y.scale_[0] # Standard deviation is sqrt of diagonal
    
#     # Calculate Relative Error
#     relative_error = np.abs(y_test_sorted - y_pred) / y_test_sorted

#     # ==========================================
#     # PLOT 1: EMPIRICAL VS BLACK BOX & RELATIVE ERROR
#     # ==========================================
#     fig1, (ax1, ax2) = plt.subplots(2, 1, figsize=(30, 20), gridspec_kw={'height_ratios': [2, 1]})
    
#     # Top: Empirical Dots vs Black Box Predictions
#     ax1.scatter(density_test, y_test_sorted, color='black', alpha=0.7, label='Empirical (CAFM Sim Data)')
#     ax1.plot(density_test, y_pred, color='blue', linewidth=2, label='Black Box (GP Prediction)')
#     ax1.fill_between(density_test, y_pred - 2*sigma, y_pred + 2*sigma, color='blue', alpha=0.2, label='$\pm 2\sigma$ Variance')
    
#     ax1.set_title("Empirical Simulation vs GP Black Box: Density to Crossing Time")
#     ax1.set_ylabel("Mean Crossing Time (s)")
#     ax1.legend()
#     ax1.grid(True, alpha=0.3)

#     # Bottom: Relative Error
#     ax2.bar(density_test, relative_error * 100, color='red', alpha=0.6, width=0.01)
#     ax2.axhline(np.mean(relative_error * 100), color='black', linestyle='--', label=f'Mean Error: {np.mean(relative_error*100):.2f}%')
#     ax2.set_title("Relative Error (%) across Density")
#     ax2.set_xlabel("Density (ped/m²)")
#     ax2.set_ylabel("Error (%)")
#     ax2.legend()
#     ax2.grid(True, alpha=0.3)
    
#     plt.tight_layout()
#     plt.savefig("plot1_empirical_vs_blackbox.png", dpi=300)

#     # ==========================================
#     # PLOT 2: INTERNAL GP MECHANICS (COVARIANCE KERNEL)
#     # ==========================================
#     fig2, ax3 = plt.subplots(figsize=(8, 7))
    
#     # We plot the absolute Correlation/Covariance Matrix generated by the Kernel
#     # This shows mathematically how the GP relates different density points to each other
#     cov_heatmap = ax3.imshow(y_cov_scaled, cmap='inferno', interpolation='nearest')
#     fig2.colorbar(cov_heatmap, ax=ax3, label='Kernel Covariance Strength')
    
#     ax3.set_title("Internal GP Mathematics: Covariance Matrix Heatmap")
#     ax3.set_xlabel("Test Sample Index (Sorted by Density)")
#     ax3.set_ylabel("Test Sample Index (Sorted by Density)")
    
#     plt.tight_layout()
#     plt.savefig("plot2_gp_covariance_matrix.png", dpi=300)
    
#     print("\n--- DEEP STUDY RESULTS ---")
#     print("Generated Plot 1: plot1_empirical_vs_blackbox.png")
#     print("Generated Plot 2: plot2_gp_covariance_matrix.png")
#     print(f"Average Relative Error: {np.mean(relative_error)*100:.2f}%")
#     print("Scaling applied: YES (StandardScaler on X and Y)")




# import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.gaussian_process import GaussianProcessRegressor
# from sklearn.gaussian_process.kernels import Matern, ConstantKernel, WhiteKernel
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

# def supervisor_covariance_analysis(data_path):
#     print("Loading data and training the 6D GP...")
#     data = np.load(data_path)
#     X_raw, Y_raw = data['X'], data['Y']
    
#     # Clean data (Target = mean_crossing_time)
#     y = Y_raw[:, 0]
#     valid_mask = ~np.isnan(y)
#     X_clean, y_clean = X_raw[valid_mask], y[valid_mask]
    
#     # Scale Data
#     scaler_X = StandardScaler()
#     scaler_y = StandardScaler()
#     X_scaled = scaler_X.fit_transform(X_clean)
#     y_scaled = scaler_y.fit_transform(y_clean.reshape(-1, 1)).ravel()

#     # Train GP
#     kernel = ConstantKernel(1.0) * Matern(length_scale=np.ones(6), nu=2.5) + WhiteKernel(noise_level=0.1)
#     gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=5, random_state=42)
#     gp.fit(X_scaled, y_scaled)
#     print(f"Learned Kernel: {gp.kernel_}")

#     # =====================================================================
#     # CREATING A PURE 1D SWEEP FOR DEEP ANALYSIS
#     # Lock 5 parameters at their mean, sweep ONLY density (idx=4)
#     # This gives us a mathematically clean line to study covariance
#     # =====================================================================
#     n_points = 100
#     X_sweep = np.tile(np.mean(X_clean, axis=0), (n_points, 1)) # Baseline
#     density_values = np.linspace(np.min(X_clean[:, 4]), np.max(X_clean[:, 4]), n_points)
#     X_sweep[:, 4] = density_values # Sweep density
    
#     X_sweep_scaled = scaler_X.transform(X_sweep)
    
#     # Extract Mean and Covariance Matrix
#     y_mean_scaled, y_cov_scaled = gp.predict(X_sweep_scaled, return_cov=True)
#     y_mean = scaler_y.inverse_transform(y_mean_scaled.reshape(-1, 1)).ravel()
    
#     # Standard deviation is the square root of the diagonal of the Covariance matrix
#     sigma_scaled = np.sqrt(np.diag(y_cov_scaled))
#     sigma = sigma_scaled * scaler_y.scale_[0]

#     # Sample random functions directly from the Covariance Matrix (Posterior Sampling)
#     # THIS is what proves you understand GP Variance!
#     y_samples_scaled = gp.sample_y(X_sweep_scaled, n_samples=5, random_state=42)
#     y_samples = scaler_y.inverse_transform(y_samples_scaled)

#     # ==========================================
#     # PLOT 1: POSTERIOR SAMPLES & VARIANCE BANDS
#     # ==========================================
#     plt.figure(figsize=(30, 20))
    
#     # Plot the 95% confidence interval (Variance)
#     plt.fill_between(density_values, y_mean - 2*sigma, y_mean + 2*sigma, 
#                      color='lightgray', alpha=0.6, label='±2σ Variance Bound (95% Confidence)')
    
#     # Plot the 5 sampled functions drawn from the Covariance Matrix
#     colors = ['red', 'blue', 'green', 'orange', 'purple']
#     for i in range(5):
#         plt.plot(density_values, y_samples[:, i], color=colors[i], alpha=0.6, 
#                  lw=1.5, label=f'Sampled Function {i+1}' if i==0 else "")
                 
#     # Plot the Mean Prediction
#     plt.plot(density_values, y_mean, 'k--', lw=3, label='GP Mean Prediction')
    
#     plt.title("Variance Analysis: Functions Sampled from the GP Posterior")
#     plt.xlabel("Density (ped/m²)")
#     plt.ylabel("Mean Crossing Time (s)")
#     plt.legend()
#     plt.grid(True, linestyle=':', alpha=0.7)
#     plt.tight_layout()
#     plt.savefig("analysis1_posterior_samples.png", dpi=300)

#     # ==========================================
#     # PLOT 2: COVARIANCE MATRIX HEATMAP
#     # ==========================================
#     plt.figure(figsize=(8, 7))
#     # Remove the white noise from the diagonal for a cleaner view of the structural covariance
#     cov_no_noise = y_cov_scaled - np.eye(n_points) * gp.kernel_.k2.noise_level
    
#     im = plt.imshow(cov_no_noise, cmap='inferno', interpolation='nearest', 
#                     extent=[density_values[0], density_values[-1], density_values[-1], density_values[0]])
#     plt.colorbar(im, label='Covariance Strength')
#     plt.title("The Matern Covariance Matrix K(X,X')")
#     plt.xlabel("Density")
#     plt.ylabel("Density")
#     plt.tight_layout()
#     plt.savefig("analysis2_covariance_heatmap.png", dpi=300)

#     # ==========================================
#     # PLOT 3: COVARIANCE DECAY VS DISTANCE (THE ULTIMATE PROOF)
#     # ==========================================
#     plt.figure(figsize=(8, 5))
    
#     # Take the middle point (index 50) and see how it correlates with all other points
#     mid_idx = 50
#     mid_density = density_values[mid_idx]
    
#     # Calculate physical distance from the midpoint
#     distances = np.abs(density_values - mid_density)
    
#     # Extract the covariance values for that specific row
#     cov_values = cov_no_noise[mid_idx, :]
    
#     plt.plot(distances, cov_values, 'crimson', lw=3)
#     plt.fill_between(distances, 0, cov_values, color='crimson', alpha=0.2)
#     plt.title("Covariance Decay: How relation drops with Distance")
#     plt.xlabel(f"Absolute Distance from Density = {mid_density:.2f}")
#     plt.ylabel("Covariance Magnitude")
#     plt.grid(True, linestyle=':', alpha=0.7)
#     plt.tight_layout()
#     plt.savefig("analysis3_covariance_decay.png", dpi=300)

#     print("\n--- VISUAL ANALYSIS GENERATED ---")
#     print("1. analysis1_posterior_samples.png (Visualizing Variance)")
#     print("2. analysis2_covariance_heatmap.png (The Covariance Matrix)")
#     print("3. analysis3_covariance_decay.png (Distance vs Covariance)")


# if __name__ == "__main__":
#     run_deep_study(data_path)
#     supervisor_covariance_analysis(data_path)


import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, ConstantKernel, WhiteKernel, RBF
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error
import warnings

# Ignore minor warnings for a clean terminal output
warnings.filterwarnings("ignore")

def run_6d_real_world_analysis(data_path):
    print("="*60)
    print("PART 1: REAL-WORLD 6D GP ANALYSIS (Partial Dependence)")
    print("="*60)
    
    # 1. Load Data
    data = np.load(data_path)
    X_raw, Y_raw = data['X'], data['Y']
    
    density_idx = 4
    target_idx = 0
    
    y = Y_raw[:, target_idx]
    valid_mask = ~np.isnan(y)
    X_clean, y_clean = X_raw[valid_mask], y[valid_mask]
    
    X_train, X_test, y_train, y_test = train_test_split(X_clean, y_clean, test_size=0.2, random_state=42)
    
    sorted_idx = np.argsort(X_test[:, density_idx])
    X_test_sorted = X_test[sorted_idx]
    y_test_sorted = y_test[sorted_idx]
    density_test = X_test_sorted[:, density_idx]

    # 2. Scale Data
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_test_scaled = scaler_X.transform(X_test_sorted)
    y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

    # 3. Train Full 6D Model (Captures actual physics)
    kernel = ConstantKernel(1.0) * Matern(length_scale=np.ones(6), nu=2.5) + WhiteKernel(noise_level=0.1)
    gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10, random_state=42)
    gp.fit(X_train_scaled, y_train_scaled)

    # 4. Numerical Metrics (For your report)
    y_pred_scaled, _ = gp.predict(X_test_scaled, return_std=True)
    y_pred_test = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
    
    relative_error = np.abs(y_test_sorted - y_pred_test) / y_test_sorted
    
    print("\n--- TEST SET METRICS ---")
    print(f"R-Squared (R²):        {r2_score(y_test_sorted, y_pred_test):.4f}")
    print(f"RMSE:                  {root_mean_squared_error(y_test_sorted, y_pred_test):.4f} s")
    print(f"Mean Absolute Error:   {mean_absolute_error(y_test_sorted, y_pred_test):.4f} s")
    print(f"Mean Relative Error:   {np.mean(relative_error)*100:.2f} %")

    # 5. The Partial Dependence Sweep (Lock 5, Sweep 1)
    n_points = 150
    X_sweep = np.tile(np.mean(X_clean, axis=0), (n_points, 1))
    density_sweep = np.linspace(np.min(X_clean[:, density_idx]), np.max(X_clean[:, density_idx]), n_points)
    X_sweep[:, density_idx] = density_sweep
    
    X_sweep_scaled = scaler_X.transform(X_sweep)
    y_sweep_scaled, y_sweep_cov = gp.predict(X_sweep_scaled, return_cov=True)
    y_sweep_mean = scaler_y.inverse_transform(y_sweep_scaled.reshape(-1, 1)).ravel()
    sigma_sweep = np.sqrt(np.diag(y_sweep_cov)) * scaler_y.scale_[0]

    cov_no_noise = y_sweep_cov - np.eye(n_points) * gp.kernel_.k2.noise_level

    # ==========================================
    # PLOT 1: Empirical vs Black Box & Error
    # ==========================================
    fig1, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), gridspec_kw={'height_ratios': [2, 1]})
    
    ax1.scatter(density_test, y_test_sorted, color='black', alpha=0.7, label='Empirical CAFM Test Data')
    ax1.plot(density_sweep, y_sweep_mean, color='royalblue', linewidth=2.5, label='6D GP Black Box (Projected)')
    ax1.fill_between(density_sweep, y_sweep_mean - 2*sigma_sweep, y_sweep_mean + 2*sigma_sweep, color='royalblue', alpha=0.2, label='$\pm 2\sigma$ Uncertainty')
    ax1.set_title("Real-World 6D GP: Empirical Data vs Black Box Projection")
    ax1.set_ylabel("Mean Crossing Time (s)")
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.bar(density_test, relative_error * 100, color='crimson', alpha=0.6, width=0.01)
    ax2.axhline(np.mean(relative_error * 100), color='black', linestyle='--', label=f'Mean Error: {np.mean(relative_error*100):.2f}%')
    ax2.set_title("Relative Error (%) of GP Predictions")
    ax2.set_xlabel("Density (ped/m²)")
    ax2.set_ylabel("Error (%)")
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig("plot_1_empirical_and_error.png", dpi=300)

    # ==========================================
    # PLOT 2: Covariance Matrix & Decay Math
    # ==========================================
    fig2, (ax3, ax4) = plt.subplots(1, 2, figsize=(16, 6))
    
    im = ax3.imshow(cov_no_noise, cmap='inferno', interpolation='nearest', extent=[density_sweep[0], density_sweep[-1], density_sweep[-1], density_sweep[0]])
    fig2.colorbar(im, ax=ax3, label='Covariance Strength')
    ax3.set_title("Matern Covariance Matrix Heatmap K(X,X')")
    ax3.set_xlabel("Density")
    ax3.set_ylabel("Density")
    
    mid_idx = n_points // 2
    mid_density = density_sweep[mid_idx]
    distances = np.abs(density_sweep - mid_density)
    ax4.plot(distances, cov_no_noise[mid_idx, :], 'crimson', lw=3)
    ax4.fill_between(distances, 0, cov_no_noise[mid_idx, :], color='crimson', alpha=0.2)
    ax4.set_title("Matern Covariance Decay over Distance")
    ax4.set_xlabel(f"Distance from Mid-Density ({mid_density:.2f})")
    ax4.set_ylabel("Covariance Magnitude")
    ax4.grid(True, linestyle=':', alpha=0.6)
    
    plt.tight_layout()
    plt.savefig("plot_2_covariance_math.png", dpi=300)
    print("Real-world plots saved (plot_1_empirical_and_error.png, plot_2_covariance_math.png)")


def run_1d_textbook_leaf_plot():
    print("\n" + "="*60)
    print("PART 2: THE TEXTBOOK 'LEAF' (Zero-Variance Proof)")
    print("="*60)
    
    # 1. Toy Data designed to mimic CAFM density behavior perfectly
    X_train = np.array([[0.1], [0.3], [0.45], [0.7], [0.85], [1.0]])
    y_train = np.array([7.0, 9.5, 11.0, 15.0, 13.5, 18.0])
    
    # 2. Pure Noise-Free GP (alpha=1e-10 forces interpolation)
    kernel = RBF(length_scale=0.15)
    gp = GaussianProcessRegressor(kernel=kernel, alpha=1e-10, n_restarts_optimizer=10)
    gp.fit(X_train, y_train)
    
    X_sweep = np.linspace(0.0, 1.1, 200).reshape(-1, 1)
    y_mean, y_cov = gp.predict(X_sweep, return_cov=True)
    sigma = np.sqrt(np.diag(y_cov))
    
    # Sample Posterior Functions
    np.random.seed(42)
    y_samples = np.random.multivariate_normal(y_mean, y_cov, size=5).T

    # ==========================================
    # PLOT 3: The Leaf Pattern
    # ==========================================
    plt.figure(figsize=(12, 7))
    
    plt.fill_between(X_sweep.ravel(), y_mean - 2*sigma, y_mean + 2*sigma, color='lightblue', alpha=0.6, label='$\pm 2\sigma$ Variance (Pinches to 0 at data)')
    
    colors = ['crimson', 'forestgreen', 'darkorange', 'purple', 'gold']
    for i in range(5):
        plt.plot(X_sweep, y_samples[:, i], color=colors[i], alpha=0.7, lw=1.5, label=f'Sampled Function {i+1}' if i==0 else "")
                 
    plt.plot(X_sweep, y_mean, 'b--', lw=2.5, label='GP Mean ($\mu$)')
    plt.plot(X_train, y_train, 'ko', markersize=8, zorder=10, label='Empirical Nodes (Zero Uncertainty)')
    
    plt.title("Textbook GP Proof: Posterior Sampling and Variance 'Pinching'", fontsize=14, pad=15)
    plt.xlabel("Density (ped/m²)", fontsize=12)
    plt.ylabel("Mean Crossing Time (s)", fontsize=12)
    plt.legend(fontsize=10, loc='upper left')
    plt.grid(True, linestyle=':', alpha=0.7)
    
    plt.tight_layout()
    plt.savefig("plot_3_textbook_leaf.png", dpi=300)
    print("Textbook proof saved (plot_3_textbook_leaf.png)")



def run_failed_leaf_with_real_data(data_path):
    print("\n" + "="*60)
    print("PART 4: THE 'THICK BLOB' (Why real 6D data fails the 1D Leaf test)")
    print("="*60)
    
    # 1. Load the REAL Data
    data = np.load(data_path)
    X_raw, Y_raw = data['X'], data['Y']
    
    # Extract ONLY Density (1D) and Crossing Time (1D)
    density_idx = 4
    target_idx = 0
    valid_mask = ~np.isnan(Y_raw[:, target_idx])
    X_clean_1D = X_raw[valid_mask, density_idx].reshape(-1, 1) # Forced into 1D!
    y_clean = Y_raw[valid_mask, target_idx]

    # 2. Scale
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()
    X_scaled = scaler_X.fit_transform(X_clean_1D)
    y_scaled = scaler_y.fit_transform(y_clean.reshape(-1, 1)).ravel()

    # 3. Train a pure 1D GP on the real noisy data
    # We MUST include WhiteKernel. If we used alpha=1e-10 (noise-free) here, 
    # the math would instantly crash (LinAlgError) because real data has 
    # different Y values for the same X value!
    kernel = ConstantKernel(1.0) * RBF(length_scale=1.0) + WhiteKernel(noise_level=0.5)
    gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10, random_state=42)
    gp.fit(X_scaled, y_scaled)
    
    # 4. Sweep and Extract Covariance
    X_sweep = np.linspace(np.min(X_clean_1D), np.max(X_clean_1D), 150).reshape(-1, 1)
    X_sweep_scaled = scaler_X.transform(X_sweep)
    
    y_mean_scaled, y_cov_scaled = gp.predict(X_sweep_scaled, return_cov=True)
    y_mean = scaler_y.inverse_transform(y_mean_scaled.reshape(-1, 1)).ravel()
    sigma = np.sqrt(np.diag(y_cov_scaled)) * scaler_y.scale_[0]
    
    # 5. Sample the Posterior (Including the noise, which causes the blob)
    np.random.seed(42)
    y_samples_scaled = np.random.multivariate_normal(y_mean_scaled, y_cov_scaled, size=5).T
    y_samples = scaler_y.inverse_transform(y_samples_scaled)

    # ==========================================
    # PLOT: THE MASSIVE BLOB
    # ==========================================
    plt.figure(figsize=(12, 7))
    
    # Notice the Variance band is huge and NEVER pinches to zero!
    plt.fill_between(X_sweep.ravel(), y_mean - 2*sigma, y_mean + 2*sigma, 
                     color='lightcoral', alpha=0.3, label='$\pm 2\sigma$ Massive Aleatoric Uncertainty')
    
    # The samples will look like a chaotic scribble (spaghetti)
    colors = ['red', 'darkred', 'orange', 'purple', 'brown']
    for i in range(5):
        plt.plot(X_sweep, y_samples[:, i], color=colors[i], alpha=0.7, lw=1.5)
                 
    plt.plot(X_sweep, y_mean, 'k--', lw=3, label='GP Mean (Flattens out)')
    
    # The real data points, scattered everywhere
    plt.scatter(X_clean_1D, y_clean, color='black', alpha=0.4, s=20, label='Real LHS Data (Creates Noise)')
    
    plt.title("The 'Thick Blob': Attempting a 1D Posterior on Noisy 6D Real Data", fontsize=14, pad=15)
    plt.xlabel("Density (ped/m²)", fontsize=12)
    plt.ylabel("Mean Crossing Time (s)", fontsize=12)
    plt.legend(fontsize=10, loc='upper left')
    plt.grid(True, linestyle=':', alpha=0.7)
    
    plt.tight_layout()
    filename = "plot_4_failed_blob_real_data.png"
    plt.savefig(filename, dpi=300)
    print(f"Failed Blob visualization saved as: {filename}")


if __name__ == "__main__":
    DATA_PATH = r"D:\KIT\cafm_lhs_1000.npz"
    
    try:
        run_6d_real_world_analysis(DATA_PATH)
        run_1d_textbook_leaf_plot()
        run_failed_leaf_with_real_data(DATA_PATH) # <--- ADD THIS LINE
        print("\nSUCCESS! All analyses are complete and ready for the supervisor meeting.")
    except FileNotFoundError:
        print(f"\nERROR: Could not find the file at {DATA_PATH}. Please check the path and try again.")